

airbyte.check:
	.venv/bin/python main.py check --config secrets/config.json

airbyte.discover:
	.venv/bin/python main.py discover --config secrets/config.json

airbyte.read:
	.venv/bin/python main.py read --config secrets/config.json --catalog integration_tests/configured_catalog.json

